config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :rounds, only: [:create, :show, :destroy] do
    resources :restaurants, only: [:create, :update]
    get 'start' => 'rounds#start'
  end

  get 'find_key' => 'rounds#find_key'
  get 'rounds/:id/results' => 'rounds#results'
  get ':key' => 'rounds#find_key'
  put '/rounds/:id/finish_voting' => 'rounds#finish_voting'
  post '/rounds/:id/send_text' => 'rounds#send_text'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :round

  validates :name, presence: true
end

app/models/round.rb
# require 'securerandom'

class Round < ApplicationRecord

  has_many :restaurants, dependent: :destroy
  has_many :users, dependent: :destroy

  def self.makeKey
    (0...5).map { ('A'..'Z').to_a[rand(26)] }.join
    # SecureRandom.urlsafe_base64(3)
  end

  def vote_url
    "whatshouldweeat.herokuapp.com/#{self.key}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  belongs_to :round
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    reset_session
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def update
    restaurant = Restaurant.find(params[:id])
    votes = restaurant.votes
    restaurant.update_attribute(:votes, votes + 1)
    session[params[:name]] = true
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
skip_before_action :verify_authenticity_token

  def create
    location = {lat: params[:lat], lng: params[:lng], radius: params[:radius]}
    round = Round.create
    session[:creator] = true
    if location && round.save
      short_url = helpers.shorten_url("whatshouldweeat.herokuapp.com/rounds/#{round.id}")
      round.update_attribute(:key, short_url)
      helpers.get_restaurants(round, location)
      if round.restaurants.length > 0
        redirect_to round
      else
        @error = "No results!"
        flash.now[:notice] = 'No results!'
        render 'home/index'
      end
    else
      redirect_to '/'
    end
  end

  def show
    @round = Round.find(params[:id])
    if @round.completed
      @winner = @round.restaurants.find_by(winner: :true)
      render 'results'
    else
      if session[:user_id].nil?
        @user = User.create(name: 'abc', round_id: params[:id])
        session[:user_id] = @user.id
      else
        @user = User.find_by(id: session[:user_id])
        if @user
          @user
        else
          @user = User.create(name: 'abc', round_id: params[:id])
          session[:user_id] = @user.id
          session[:voted] = nil
        end
      end
      render 'show'
    end
  end


  def destroy
  end

  def find_key
    @round = Round.find_by(key: params[:key])
    if @round
      redirect_to @round
    else
      redirect_to '/'
    end
  end

  def start
    @round = Round.find(params[:round_id])
    @restaurants = @round.restaurants
  end

  def results
    @round = Round.find(params[:id])
    @round.update_attribute(:completed, true)
    @winner = @round.restaurants.order(votes: :desc).limit(1).first
    @winner.update_attribute(:winner, true)
    @winner_page = render 'rounds/results', locals: { winner: @winner }
    ActionCable.server.broadcast "rounds_channel_#{@round.id}",
                                  body: @winner_page
    @round.users.each{|u| u.destroy}
    @round.restaurants.where(winner: nil).each{ |r| r.destroy}
  end

  def finish_voting
    @round = Round.find(params[:id])

    if session[:voted].nil?
      session[:voted] = true
      count = @round.finished_voting_count
      @round.update_attribute(:finished_voting_count, count + 1)
    end

    new_count = @round.finished_voting_count
    total_users = @round.users.count
    ActionCable.server.broadcast "rounds_channel_#{@round.id}",
                                  checked: true,
                                  finished_count: new_count,
                                  total_users: total_users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/price_helper.rb
module PriceHelper
    def price_to_sign(price)
      case price
        when 1
          "$"
        when 2
          "$$"
        when 3
          "$$$"
        when 4
          "$$$$"
        when 5
          "$$$$$"
        else
          "N/A"
      end
    end

  def rating_to_star(rating)
    case rating
      when 1..2
        "&#9733&frac12".html_safe
      when 2..2.5
        "&#9733&frac12".html_safe
      when 2.5..3
        "&#9733&frac34".html_safe
      when 3..3.5
        "&#9733&#9733&#9733&frac12".html_safe
      when 3.5..4
        "&#9733&#9733&#9733&frac34".html_safe
      when 4..4.5
        "&#9733&#9733&#9733&#9733&frac12".html_safe
      when 4..4.5
        "&#9733&#9733&#9733&#9733&frac34".html_safe
      when 4.5..5
        "&#9733&#9733&#9733&#9733&#9733".html_safe
      else
        "N/A"
    end

  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  def get_restaurants(round, location)
    response = RestClient.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{location[:lat]},#{location[:lng]}&radius=#{location[:radius]}&type=restaurant&key=#{ENV["GOOGLE_PLACES_TOKEN"]}")
    response = JSON.parse(response)
    # additional_results(response, round) # Google places API call returns 20 results max, can use this method to get more, but makes things much slower
    create_restaurants(response, round)
  end

  # def get_location(location)
  #   @location = RestClient.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{location[:street]},+#{location[:city]},+#{location[:state]}&key=#{ENV["GOOGLE_GEOCODING_TOKEN"]}")
  #   @location = JSON.parse(@location)
  #   if @location["status"] == "ZERO_RESULTS"
  #     return nil
  #   end
  #   @lat = @location["results"][0]["geometry"]["location"]["lat"]
  #   @lng = @location["results"][0]["geometry"]["location"]["lng"]
  #   {lat: @lat, lng: @lng}
  # end

  def shorten_url(url)
    new_url = RestClient.post "https://www.googleapis.com/urlshortener/v1/url?key=#{ENV["GOOGLE_URL_TOKEN"]}", { "longUrl": url }.to_json, {content_type: 'application/json'}
    new_url = JSON.parse(new_url)
    new_url["id"]
  end

  def valid_location?(location)
    !@location["status"] == "ZERO_RESULTS"
  end

  def additional_results(response, round)
    if response['next_page_token']
      sleep(1.5) # Can't call the API too quickly with a pagetoken query or it returns invalid request
      more_restaurants = RestClient.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?pagetoken=#{response['next_page_token']}&key=#{ENV["GOOGLE_PLACES_TOKEN"]}")
      more_restaurants = JSON.parse(more_restaurants)
      additional_results(more_restaurants, round)
      create_restaurants(more_restaurants, round)
    end
  end

  def create_restaurants(json_response, round)
    response = json_response["results"]
    response.each do |restaurant|
      Restaurant.create(name: restaurant["name"], rating: restaurant["rating"], price: restaurant["price_level"], address: restaurant["vicinity"], round_id: round.id)
    end
  end
end

app/views/home/_form.html.erb
<%= form_for @rounds do |f| %>
	<% if @rounds.errors.any? %>
		<div>
			<h2><%= pluralize(@rounds.errors.count, "error") %> prohibited the round from being made:</h2>
			<ul>
			<% @rounds.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<%= f.label :restaurant, "Choice of Food" %><br>
		<%= f.text_field :restaurant %> 
	</div>

	<div>
		<%= f.submit :submit, "Ready", class: "ready-button" %>
	</div>
<% end %>

app/views/home/index.html.erb
<div class='error-container'>
  <% if @error %>
    <% puts "I was reached, @error is #{@error}" %>
    <p><%= @error %></p>
  <% end %>

  <% flash.each do |key, value| %>
    <% puts "flash key is #{key}, flash value is #{value}" %>
    <p>test</p>
    <p><%= value %></p>
  <% end %>
</div>


<p id="welcome-message">Where indecision ends and eating begins.</p>
<div class="index-container">
  <div class="form-container">
    <div id="map"></div>
    <div class='game-instruction'>
      <p id="direction">Drop a pin on the map in the area you plan to eat</p>
      <div class="create-form">
        <%= form_tag rounds_path, method: :post, id: :'start-form' do |f| %>
          <div class="styled-select dim" id="radius-div">
          <%= label_tag "Radius:" %>
          <%= select_tag 'radius', "<option>Select radius</option><option>1/2 Mile</option><option selected=\"selected\">2 Miles</option><option>5 Miles</option><option>10 Miles</option>".html_safe %>
          </div>
        <%= submit_tag "Continue", :class => "hvr-grow-shadow submit-button", :id => "create-button", data: {disable_with: false} %>
      <% end %>
      </div>
    </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=0.5" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Whatshouldweeat</title>
    <%= csrf_meta_tags %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkb6qe0T6dFkQqUtOg7_Wgkv0e7HwSFA4&callback=initMap"
    async defer></script>
	  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="/assets/hover.css" rel="stylesheet" media="all">
    <link href='https://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Bungee Shade' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Domine:700" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="center header">
        <span class="main-title"> <%= link_to 'Kafood', root_path, id: 'header-link'%></span>
      </h1>
    </header>
    <h1>
      <% flash.each do |k, v| %>
        <div id="<%= k %>"><%= v %></div>
      <% end %>
    </h1>

    <%= yield %>
  </body>
</html>

app/views/rounds/_restaurants_list.html.erb
<div class="restaurants-container" ><!-- 1st row -->
  <% @round.restaurants.each do |r| %>

    <div class='restaurant-item <%= session[r.name] ? 'voted' : 'voteable' %> hvr-float-shadow' data-restaurant-id='<%= r.id %>' data-round-id='<%= @round.id %>'>
      <div class="center restaurant-name"><%= r.name %></div><br>
      <div class="center restaurant-rating"> <%= rating_to_star(r.rating)  %></div><br>
      <div class="center restaurant-price"> <%= price_to_sign(r.price) %></div>
    </div>
  <% end %>
</div>

app/views/rounds/results.html.erb
<div class="center results-container">
    <div id="name-container"> <div class="hvr-grow-shadow" id="winner-name"><%= @winner.name %></div></div>
    <div id="winner-address"> Located at: <%= @winner.address %></div>
    <div id="winner-website"><%= link_to "Info", "http://www.google.com#q=#{@winner.name.split.join('+')}" %></div>
</div>

app/views/rounds/show.html.erb
<% if session[:creator] %>
  <p id="invite-info">Share the link with other people in your party. Once everyone has placed their votes, click results to find out where you're eating!</p>
  <div class="link-container">
    <div id="game-key" data-round-id="<%= @round.id %>">
      <span class="hvr-underline-from-center hvr-grow-shadow" id='link-key'>Share This Link: <span id='link'><span id='key'><%= "goo.gl/#{@round.key[-6..-1]}" %></span></span>
    </div>
    <button id="link-copy" onclick="copyToClipboard('#link')">Copy Link</button>
  </div>
<% else %>
  <p id="invite-info">Select all the restaurants you would like to eat at then click finished voting</p>
<% end %>



<div id='container' data-round-id="<%= @round.id %>" data-user-id="<%= @user.id %>" lat-id=>
  <%= render "restaurants_list" %>
</div>

<% if !session[:creator] %>
  <div id='finish-vote'>
    <%= form_tag({controller: "rounds", action: "finish_voting"}, method: "put", id: 'vote-check') do %>
      <% if !session[:voted].nil? %>
        <%= submit_tag 'finished voting', id: 'vote-finish', class: 'submit-button hvr-grow-shadow', disabled: true %>
      <% else %>
        <%= submit_tag 'finished voting', id: 'vote-finish', class: 'submit-button hvr-grow-shadow' %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if session[:creator] %>
  <div id='creators-dashboard-container'>
    <div id='creators-dashboard'>
      <div id="round-results-btn" class="submit-button" data-round-id="<%= @round.id %>">
        <%= link_to 'Results', "/rounds/#{@round.id}/results", id: 'results-link' %>
      </div>
      <span id='finished-users' class="submit-button">0</span>
    </div>
  </div>
<% end %>